### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by captainepoch** [babun/babun#125]
Hey guys!

This is not a post when I want to uninstall Babun, BUT, in that case, how should I uninstall it?

Thanks you so much!

**Comment by glkhobragade** [comment]
there is uninstall.bat present in the  .babun  directory. Just run that.

**Comment by awci** [comment]
When I run the uninstall.bat 
shel gives that error and terminate it uninstall
0 [main] bash 7576 child_info_fork::abort: C:\Users\Administrator\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x550000) != child(0xC90000)
/etc/profile: fork: retry: No child processes
      0 [main] bash 2484 child_info_fork::abort: C:\Users\Administrator\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x550000) != child(0xD10000)
/etc/profile: fork: retry: No child processes
      2 [main] bash 2372 child_info_fork::abort: C:\Users\Administrator\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x550000) != child(0xCD0000)
/etc/profile: fork: retry: No child processes
      1 [main] bash 8456 child_info_fork::abort: C:\Users\Administrator\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x550000) != child(0xC70000)
/etc/profile: fork: retry: No child processes
      1 [main] bash 5364 child_info_fork::abort: C:\Users\Administrator\.babun\cygwin\bin\cygiconv-2.dll: Loaded to different address: parent(0x550000) != child(0xDB0000)
/etc/profile: fork: Resource temporarily unavailable
[babun] Terminating due to internal error #254

**Comment by Iakobs** [comment]
I got same error as @awci!

**Comment by distinguished-git** [comment]
Same. Malware.
