### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Bleakwise** [babun/babun#264]
groovy build.groovy release

just spits out an error.

http://i.imgur.com/LZdgRYK.png

I've also tried building Babun from within an install of Babun via GVM with the same results.

**Comment by kubamarchwicki** [comment]
I've encountered same issue while trying to build on windows (Win7, 64bit). It might be related to running 'groovy' command in `build.groovy`; changing it to groovy.bat (as we are windows) made it working. 
I found a stackoverflow description of that

**Comment by tombujok** [comment]
You need to have groovy/bin folder in PATH and it will work.

...but in order to hack around you can just adjust local files in 
/usr/local/etc/bin
/usr/local/etc/babun
/usr/local/etc/babun/source
Just make a backup of the babun instance beforehand - just zip the .babun folder.

Building your own distro and installing it takes around 30 minuts - that's a long and not recommended roundtrip...

**Comment by Bleakwise** [comment]
kubamarchwicki couldn't the script just be updated with a few if conditionals? If on windows, change the string "groovy" to "groovy.bat" ?

I'll give the groovy.bat command a go if 1.1.0 doesn't solve my problems.
