### ISSUE TITLE
Ansible doesnt work on babun 1.1.0

### ISSUE THREAD

**Issue by margielm** [babun/babun#315]
Hello,
Ansible doesnt work on babun 1.1.0. while trying to execute any module it throwing:
```
ansible all -m ping               
     11 [main] python2.7 86528 child_info_fork::abort: address space needed by '_speedups.dll' (0x5B0000) is already occupied
Traceback (most recent call last):
  File "/usr/bin/ansible", line 197, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/bin/ansible", line 163, in run
    extra_vars=extra_vars,
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 233, in __init__
    cmd = subprocess.Popen(['ssh','-o','ControlPersist'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```
I know that ansible doesnt support cygwin officialy. But it is working on previous version it worked without any problems.

for me this is 100% blocker to use new version.

**Comment by tombujok** [comment]
Hej Michal :)
It looks like a python problem. Does the python version match the ansible version?
Could you try with other version (python or ansible)?

**Comment by margielm** [comment]
Hello Tomek ;)
Yup, checked that. Babun 1.0.0 has  2.7.3 and 1.10 2.7.8. I tried to make it consistent by upgrading python on 1.0.0 but it (I :) ) failed with 

```Installing python
Found package python
File ‘python-2.7.8-1.tar.xz’ already there; not retrieving.

MD5 sum did not match, exiting
```

is there any way to downgrade python on 1.1.0?

btw. thanks for babun, it makes my life easier :)

**Comment by petermac-** [comment]
Same issue with Babun 1.1.0/1.1.1 and Python 2.7.8 on Windows 8.1 x64.

**Comment by jonathanhle** [comment]
I was able to get beyond this issue by rebasing Babun's Cygwin after installing the packages needed for Ansible to work:
1) Exit babun.
2) "%SYSTEMDRIVE%:\Users\%USERNAME%\.babun\cygwin\bin\dash.exe" -c '/usr/bin/rebaseall -v'

Give it a try - maybe it'll work for you.

**Comment by madrover** [comment]
@jonathanhle that worked for me.
Thanks!

**Comment by gtback** [comment]
Running `rebaseall` did not solve the problem for me (also, I think there's a missing `\` in the path to `dash.exe`).

I am running Ansible via Vagrant, using an approach similar to [this gist](https://gist.github.com/maurizi/325387aee9ea94fbf903). It's always been a bit flaky, but is now not working 100% of the time :frowning: I'm not sure if it's a problem with Cygwin/babun though.

**Comment by gtback** [comment]
I investigated this a bit more and realized that `_speedups.dll` is provided by the `markupsafe` Python library (required by Ansible) and is not affected by `rebaseall` .

**Comment by gtback** [comment]
I got around this by installing Markupsafe explicitly without speedups (using the code in mitsuhiko/markupsafe#43) **before** installing Ansible.

```
git clone git@github.com:gtback/markupsafe.git
cd markupsafe
git checkout restore-speedups-feature
python setup.py --without-speedups install
...
pip install ansible
```

I don't know if there's anything that can be done in babun to fix this issue, other than making `rebaseall` look for every file ending in .dll, not just Cygwin DLLs.

**Comment by csansone** [comment]
I had to come in and thank you for sharing your work on this @gtback, this finally put an end to my headaches with this.

I also had the same error, and rebasing didn't help:
```
1 [main] python2.7 16500 child_info_fork::abort: address space needed by '_speedups.dll' (0x4B0000) is already occupied
```

A few things are different on my setup, and your fix still worked for me.

- I'm not using Vagrant or a VM, just regular SSH to outside servers that I would like to be able to do from this windows box.

- I installed my ansible into a virtualenv within Babun.

After I had already installed everything and started getting the error, I was able to just uninstall markupsafe and use yours, and it works!

```
workon ansible #using virtualenvwrapper to activate the virtual environment
pip uninstall markupsafe
git clone https://github.com/gtback/markupsafe.git
cd markupsafe
git checkout restore-speedups-feature
python setup.py --without-speedups install
```

Success! No more errors.

```
ansible webservers -i servers -m ping 

server1 | success >> {
    "changed": false,
    "ping": "pong"
}

server2 | success >> {
    "changed": false,
    "ping": "pong"
}
```

**Comment by gtback** [comment]
Glad it worked, @csansone !

@tombujok , you can probably close this, since it's not really a babun issue.

**Comment by tombujok** [comment]
Thanks!

**Comment by ariv3ra** [comment]
I've been successfully using the [pyenv ](https://github.com/yyuu/pyenv#basic-github-checkout) project within Babun & it saves me lots of headaches with python versioning.

**Comment by narration-sd** [comment]
Thanks for all your good work, Greg @gtback -- and I have something to add, perhaps explaining why many still think Ansible can't work nicely from Windows.

- First, I would underline that it's necessary to deinstall Ansible first, before you take your steps to remove and replace Markupsafe. One of your lines is a bit disconcerting, the one having --without-speedups, but all are correct. Then installing Ansible again, no more problems with markupsafte and its wierd errors. Great.

- But, then Ansible still wouldn't actually connect to the server, despite ssh itself working fine and having taken all the palliative steps on ensuring the particular key set was enabled. The problem here turns out to be dual, perhaps, first that Ansible doesn't seem to find the private key id_rsa in the expected place, ~/.ssh/id_rsa.

This was not fun to troubleshoot, as /etc/ansible/ansible,cfg was entirely missing, and then in modifying a default one available on the internet while  watching the -vvvv logging, which is very insufficient for such problems. it becomes evident that you can't cancel the -d Ansible inserts to block logging ssh itself.

What I found was that I could get Ansible to use the proper private key, by setting ssh_args. To be very clear, you _must_ use the full path including /home/username, not ~/somepath, as the shell-in-use by Ansible doesn't interpret tilde! 

    ssh_args = -i /home/narra/.ssh/id_rsa 

With this uncommented and set, Ansible can properly connect , first with -m ping, and then with ansible-playbook yml scripts.  No other settings seem required, and using -v confirms actions occur as scriptet.

Thanks again, Greg. All this is on a very up-to-date Windows 10 1607 ,and using standard installs of latest Babun and its pact install ansible. I could always have worked from a Linux VM, but doing it directly on Windows suits very well, and with the latest Docker 1.12.1 as the parallel in play. I hope this addition will  help others enjoy it, the cow yet to speak...!

**Comment by gtback** [comment]
Thanks, @narration-sd. For what it's worth, I use [this ansible-playbook shim](https://github.com/rivaros/ansible-playbook-shim) with Vagrant to get Ansible working on Windows via Cygwin. I added a few changes in [this pull request](https://github.com/rivaros/ansible-playbook-shim/pull/5); tweaking the path to the SSH key file is a major part.

**Comment by narration-sd** [comment]
Thanks also, Greg -- will have to try that, may well work more smoothly. As time allows ;), am sure you know that routine...

**Comment by narration-sd** [comment]
p.s. I took the moment to get your pull request into a repo on the main shim, and reading items w/comments there, I may have to change a few things -- or how i arranging keys -- before use. 

It does look like a fine insight on how this can work well -- thanks again, Greg.

**Comment by narration-sd** [comment]
Hi Greg -- really burning up the bytes here the last week or two, but
finally remembered to post about a problem that stopped me for a while soon
after we were talking, and of course its fix.

    https://github.com/babun/babun/issues/682

Appropriate kudos to yourself, enclosed.

All the best, and hope you've got a nice weekend planned, down time being
good...,
Clive
