### ISSUE TITLE
How to add a new command line to babun

### ISSUE THREAD

**Issue by lovedota** [babun/babun#339]
Hi friends.
I set the Window Environment -> Path
*C:\Users\lovedota\AppData\Local\Code\bin;*.
When I use **cmd** it works fine with the command line **code**
But in babun it said *zsh: command not found: code*
How to import **cmd** command to **babun**
Thanks !

**Comment by zolem** [comment]
I would think if it works anything like linux you would need to add this to your path variable. I would use something like 
```bash
PATH="/c/Users/lovedota/AppData/Local/Code/bin:$PATH"
```
If you want it to be permanent then just add this to your ~/.bashrc,~/.zshrc or other dotfile equivalent that you use.

**Comment by zolem** [comment]
I realize you actually need to type *code.cmd* and not just *code* in babun because bash doesn't know what file extensions to look for. Windows has an environment variable to tell it what extensions to try executing so you don't have to type code.cmd in the regular prompt.
You could just type
```sh
code.cmd .
```
or add this to your ~/.bashrc, ~/zshrc
```sh
alias code="code.cmd"
```

**Comment by lovedota** [comment]
@zolem 
Thanks it works !!!!
