### ISSUE TITLE
Symbolic links not working properly

### ISSUE THREAD

**Issue by zolem** [babun/babun#344]
So I use a git repo to store my vim configs and plugins as submodules and I will always clone that into a folder vimconfig in my home directory and build a symbolic link to it using 
```bash
ln -s vimconfig/.vim .vim
```
This apparently does not work well because deleting the default .vim folder breaks vim since the /etc/vimrc gets loaded and can't find the color stuff that comes with that folder but that is another issue.

So I will instead use
```bash
ln -s vimconfig/.vim/autoload .vim/autoload
ln -s vimconfig/.vim/bundle .vim/bundle
```
For some reason this also does not work because vim will not recognize the links as directories I also can't cd into those folders through the links.

The only solution that I have found to make this work is by doing the below
```bash
ln -s ~/vimconfig/.vim/autoload ~/.vim/autoload
ln -s ~/vimconfig/.vim/bundle ~/.vim/bundle
```
It is strange that I would need to use ~ to get the symbolic link to recognize a directory.

**Comment by leycec** [comment]
There are multiple competing complaints at work here. Let's unpack this.

> This apparently does not work well because deleting the default .vim folder breaks vim since the /etc/vimrc gets loaded and can't find the color stuff that comes with that folder but **that is another issue.**

Indeed, it is. I synchronize my [`vimrc` menagerie](https://github.com/leycec/vimrc) via a dotfile manager as well ([`vcsh`](https://github.com/RichiH/vcsh), commonly referred to as excellence incarnate), and recently stumbled into the same issue. Since the fix is trivial, I've submitted a separate issue documenting this in detail *and* a corresponding pull request correcting this.

Long live [Bram](https://en.wikipedia.org/wiki/Bram_Moolenaar) and Babun, for they are both good. :monkey:  

> `ln -s vimconfig/.vim/autoload .vim/autoload`
> `ln -s vimconfig/.vim/bundle .vim/bundle`
>
> For some reason this also does not work because vim will not recognize the links as directories I also can't cd into those folders through the links.

**No.** That doesn't work because POSIX. Everything is working as intended, though perhaps not as expected. This behaviour is *not* Babun's, Cygwin's, Vim's, or `ln`'s fault. It's just your garden-variety user error. Admittedly, for those unfamiliar with command-line Linux and/or OS X operation, symlinks *are* fairly cantankerous. Especially relative symlinks.

We'll get to why below. Before we do, here's the rule-of-thumb for sane relative symlink creation:

**When creating a relative symlink** (i.e., when the first path passed to `ln` is *not* prefixed by `/`), **always `cd` to the destination directory first.**

Hence, your provided example *should* have resembled:

```
cd .vim
ln -s ../vimconfig/.vim/autoload
ln -s ../vimconfig/.vim/bundle
```

"What is this mind-bending insanity?", you are probably muttering. To quote the well-written `info ln` page:

> Symbolic links can contain arbitrary strings; **a "dangling symlink"**
> **occurs when the string in the symlink does not resolve to a file.**  There
> are no restrictions against creating dangling symbolic links.  There are
> trade-offs to using absolute or relative symlinks.  An absolute symlink
> always points to the same file, even if the directory containing the
> link is moved.  However, if the symlink is visible from more than one
> machine (such as on a networked file system), the file pointed to might
> not always be the same.  A relative symbolic link is resolved in
> relation to the directory that contains the link, and is often useful in
> referring to files on the same device without regards to what name that
> device is mounted on when accessed via networked machines.
> 
> **When creating a relative symlink in a different location than the**
> **current directory, the resolution of the symlink will be different than**
> **the resolution of the same string from the current directory.**
> Therefore, many users prefer to first change directories to the location
> where the relative symlink will be created, so that tab-completion or
> other file resolution will find the same target as what will be placed
> in the symlink.
```

This issue may be merrily closed.

**Comment by zolem** [comment]
Thanks @leycec this makes a lot of sense. I suppose I figured it was an issue because doing that same thing works just fine in linux but it did not work in babun.

**Comment by leycec** [comment]
> Thanks @leycec this makes a lot of sense.

No worries! It's hecka deep voodoo.

>  I suppose I figured it was an issue because doing that same thing works just fine in linux but it did not work in babun.

In all likelihood, you *probably* prefixed paths with `~/` under Linux. I say this as – out of obsessive curiosity – I just tried this on my local Gentoo machine. It did *not* work just fine. Linux and Babun behave the exact same in this regard. Which makes sense, as both leverage the GNU coreutils version of `ln`.

Three yays for cross-platform portability! :smile:
