### ISSUE TITLE
babun No such file or directory -- /cygdrive/

### ISSUE THREAD

**Issue by lovedota** [babun/babun#359]
Hi guys
I installed it on Window, and when use babun with command line heroku, it causes error. How can i resolve this. Thanks !
```C:\Program Files (x86)\Heroku\ruby-1.9.3\bin\ruby.exe: No such file or directory -- /cygdrive/c/Program Files (x86)/Heroku/bin/heroku (LoadError)
```

**Comment by zolem** [comment]
Well first how are you accessing it? Is it in your path or are you directly calling it using the full path? Either way you are doing it try changing
```sh
/cygdrive/c/Program Files (x86)/Heroku/bin/heroku 
```
***TO***
```sh
/c/Program Files (x86)/Heroku/bin/heroku
```
You might also need to escape the spaces but I am not sure.

**Comment by lovedota** [comment]
@zolem 
The problem is when i use **window cmd** it works fine, but when i use with **babun** it causes this error. How can i config babun to not append **cygdrive** on the path. Thanks !
![1](https://cloud.githubusercontent.com/assets/417914/8142150/5fdf4936-119e-11e5-8c60-17a3c0844bd6.png)

**Comment by zolem** [comment]
So I weirdly figured this out.
Edit the file located in C:\Program Files (x86)\Heroku\bin\heroku
find this line of code:
```sh
exec "$bindir/ruby -x "$0" "$@"
```
This code uses the variable $0 to access the current file. Basically it says ruby -x /c/../heroku
This breaks it because apparently ruby is then looking for the windows path instead of the unix path. You could fix this by simply changing the line to the below
```sh
exec "$bindir/ruby" -x "C:\\Program Files (x86)\\Heroku\\bin\\heroku" "$@"
```
This fixes your current problem but I am not sure what other repercussions might arise by doing this. I would think you would be fine because this just tells ruby to run heroku using ruby instead of bash or zsh.

Let me know how it turns out for you.

**Comment by zolem** [comment]
Lol after figuring this all out and giving you the weird above hack you could have just used the .bat instead of the shell script.

just type in heroku.bat instead of heroku

**Comment by lovedota** [comment]
@zolem 
You saved my life. Thanks a lot !

**Comment by LaurensPlay** [comment]
Great help, thanks, especially Zolem.
