### ISSUE TITLE
Trouble with compdef?

### ISSUE THREAD

**Issue by nntoan** [babun/babun#382]
Hello there,

I always get this error after login to Babun shell

```bash
compdef: unknown command or service: git
compdef: unknown command or service: grep
compdef: unknown command or service: git
```

I solved this trouble by using this command

```bash
compaudit | xargs chmod g-w
```

Please help me know what had happened?

**Comment by jlupi** [comment]
So are you saying that even though the command fixes it, whenever you restart babun you are having the same problem?

Try this: http://babun.github.io/faq.html#_i_see_compdef_unknown_command_or_service_git

See also https://github.com/robbyrussell/oh-my-zsh/issues/630

If this doesn't help you may also want to update oh-my-zsh.

**Comment by jlupi** [comment]
This duplicates https://github.com/babun/babun/issues/347 and https://github.com/babun/babun/issues/159

The fix for this was submitted by @leycec in https://github.com/robbyrussell/oh-my-zsh/pull/3889/files 
Awaitng approval from oh-my-zsh team. 

Feel free to reopen if you think that this is not the same issue.
