### ISSUE TITLE
Windows environment variables not correct

### ISSUE THREAD

**Issue by favetelinguis** [babun/babun#389]
I have noticed that when I run babun it does not use the same environment variables as i have in Widows.

For example my JAVA_OPTS does not match with what is shown hen I do printenv | grep JAVA_OPTS.
Is this expected and if it is how come?

**Comment by favetelinguis** [comment]
I have just observed that cygwin is working correct and is using the expected variables as set in Windows.

**Comment by nkoder** [comment]
@favetelinguis I've observed that variables set up "inside" Babun overwrite variables set in Windows. Moreover, searching for ```JAVA_OPTS``` in babun repo gives 3 results (see: https://github.com/babun/babun/search?utf8=%E2%9C%93&q=JAVA_OPTS ). So... my conclusion is that somewhere inside Babun ```JAVA_OPTS``` is set and if we want (I want it too! :-) ) to have custom JAVA_OPTS we have to find it and remove it ;-)

**Comment by favetelinguis** [comment]
Hmm the question is why do JAVA_OPTS need to be set at al in the .babunrc and would it be possible to just remove it? Seems like a simple fix? :)

**Comment by jlupi** [comment]
@favetelinguis @nkoder  You guys are right. In babun we do not really need JAVA_OPTS. Not sure why it is there, must be a glitch we have't notice in initial commit. I'll remove it from the code. The only thing is that we cannot fix it when you update babun automatically because we never modify files in user's home directory, i.e. we do not want to modify your .babunrc or .bashrc etc. files.

This means that you have to remove it from there manually. Sorry for that and thanks for pointing it out!

**Comment by jlupi** [comment]
Fixed in #393

**Comment by nkoder** [comment]
Stupid me! :-D
I was searching for some "internal" `.babunrc` with `JAVA_OPTS` set, something about `/etc/` or `/usr/` or whatever etc. And I missed that according to [this instruction]( https://github.com/babun/babun#tweaking-the-configuration ) proper `.babunrc` is located `$HOME`

BTW: thanks for deleting this `JAVA_OPTS` overwrite for future releases.
