### ISSUE TITLE
How to open babun from total commander in the same directory

### ISSUE THREAD

**Issue by melihovv** [babun/babun#395]
Hello! I want to run babun from total commander and I don't know how to do it. Before I used Git Bash and it opened by hotkey without any problems in the same directory. I just simply passed current path from total commander to cmder, which launched Git Bash.
I don't want to use context menu, it is not comfortable.
Can I pass path where to start to babun the same way? I also integrated babun with cmder.
Also I want to use babun from WebStorm terminal, but it launch always at home folder.

**Comment by FichteFoll** [comment]
If #398 is merged, you can simply configure the command in TotalCmd to run `babun.bat %P` or `babun.bat --here` (assuming this is available on your PATH, otherwise `C:\Users\<user>\.babun\babun.bat %P`).

Until then, you need to set the command to run `"C:\Users\<user>\.babun\cygwin\bin\mintty.exe /bin/env CHERE_INVOKING=1 /bin/zsh.exe`.

**Comment by melihovv** [comment]
I tryed, but it doen't work.
Perhabs #398 hasn't been yet merged.

**Comment by FichteFoll** [comment]
No, it hasn't since I just proposed it.

The last command in my comment should work regardless.

**Comment by melihovv** [comment]
Oh, yeah, it works!)) Thanks!
But every time it outputs warnings (image attached)
You have the same? Or I need reinstall babun
![capture](https://cloud.githubusercontent.com/assets/8608721/8755540/49e11a14-2cd4-11e5-8a01-c647c2f08bf4.PNG)

**Comment by melihovv** [comment]
I reinstalled babun and there are no warnings now. I'm happy))

**Comment by tombujok** [comment]
Thx.
