### ISSUE TITLE
can't open atom

### ISSUE THREAD

**Issue by luisrudge** [babun/babun#429]
![image](https://cloud.githubusercontent.com/assets/941075/9581963/f2e5dbf0-4fd8-11e5-9100-7ab8841292db.png)

**Comment by Berrayti** [comment]
Having almost the same problem, but with the Laravel installer 

Could not open input file: /cygdrive/c/Users/Berrayti/AppData/Roaming/Composer/vendor/laravel/installer/laravel

**Comment by jlupi** [comment]
@luisrudge in your case it looks like the atom.sh script contains windows EOL (crlf) instead of UNIX EOL (cr). Try running dos2unix on the atom sh file (files)

@Berrayti in your case i assume there is a problem with the path to the input file which is in cygwin/unix format istead of in windows format. Try `cygpath -w /cygdrive/c/Users.../...`. You may want to create an alias for that.

**Comment by Berrayti** [comment]
The solution of my problem, is that it can't know to execute the .exe or .bat, so I have to be more explicit and tape laravel.bat, and it worked. I just found the solution

**Comment by polidore** [comment]
i did:
alias atom=atom.cmd

in .zshrc

it it fixed the issue for me.

**Comment by thomasLevans** [comment]
+ @polidore
