### ISSUE TITLE
"C:"' is not recognized as an internal or external command (Installation failure)

### ISSUE THREAD

**Issue by LoLei** [babun/babun#432]
```
C:\babun-1.2.0>install.bat
[babun] Installing babun
'cscript //Nologo "C:/babun-1.2.0//dist/freespace.vbs" "C:"' is not recognized as an internal or external command,
operable program or batch file.
1024 was unexpected at this time.
```

OS: Windows 7 64bit

Would be great if I could get some insight why this isn't working. I actually installed it on the same day on a very similar environment on my work PC.

I'll try to build it myself if it can't be fixed.

**Comment by yjoung** [comment]
I'm having similar issues. Not quite sure what's going on with it.

**Comment by sanwuwy** [comment]
I have a similar issue as you @LoLei, and i finally fix it.
This issue on my PC(Windows10-64bit) is because i used to install babun on "C:\babun\.babun" and uninstall it. But the "C:\babun\.babun" was not remove in PATH. 
When i remove "C:\babun\.babun" from PATH, this issue is fixed and now i reinstall babun successfully on "C:\User\myname\.babun".
