### ISSUE TITLE
No uninstall.bat present in distribution - contrary to what it is stated in the FAQs

### ISSUE THREAD

**Issue by nullp01nt3r** [babun/babun#452]
Please:

* correct the FAQs
* or, add the missing `uninstall.bat`

BTW, so how I am supposed to uninstall Babun?

**Comment by pertrai1** [comment]
+1

**Comment by jlupi** [comment]
Hi @nullp01nt3r. Thanks for reporting.

To me it looks like either:
- you installed the old version of babun
- the uninstall.bat for some reason could not be extracted/copied while installation

Which version did you download ? The uninstall.bat should be there since version 1.2.0.

Can you check if the `uninstall.bat`
- it exist in the installation directory, ex. `%USERPROFILE%\.babun
- it exist in the installation zip you downloaded, ex; `babun-1.2.0-dist\babun-1.2.0\dist\babun.zip\.babun\`

BTW If you installed the babun version prior to 1.2.0 just delete the babun folder. If you installed version 1.2.0 and the `uninstall.bat` is missing for some reason run `babun shell-here remove` to clean up some reg entries and than delete the babun folder.

**Comment by nullp01nt3r** [comment]
Hi @jlupi,

I misunderstood what's the "installation" directory: I was looking into the very same folder where I found the install.bat (i.e. the folder wher I unzipped the babun package).

The uninstall.bat is actually where you said - i.e. in `%USERPROFILE%.babun` (I installed 1.2.0).

My bad, thank you for clarifying.
