### ISSUE TITLE
can not ssh to github

### ISSUE THREAD

**Issue by lorvent** [babun/babun#460]
Hello,
I have been using babun for bitbucket without any problems

but when i try to connect to github through ssh, it says Permission denied (public key)

but if i try with git-bash its working properly.

what could be the problem?

thanks.

**Comment by divmgl** [comment]
Git Bash uses a different directory than Babun. You need to regenerate your RSA key or copy it over from your Git Bash directory. Since I rather just generate a new RSA key and add it to my Github account, here's how to do that in Babun.

* `ssh-keygen` - This generates a new key. If you want to password protect your RSA key, enter a passphrase.
* `cat ~/.ssh/id_rsa.pub` - This will print out your new RSA key. Copy that key and go into Github and add it.

**Comment by lorvent** [comment]
Note: I am using windows environment

When i try to generate ssh using ````ssh-keygen```` both gitbash and babun creating at same location ````/home/<username>/.ssh/id_rsa````

so if i try to generate using babub, my old one(generated by gitbash) will be over-written
then i will not be able to use gitbash for github which i don't want to do.

any work around?

thanks,

**Comment by divmgl** [comment]
`/home` for Git Bash and `/home` for Babun will usually be different. Are you sure you're using the same `/home` directory? For Babun, it will usually be `%USERPROFILE%\.babun\cygwin\home'. If you've confirmed that Git Bash is pointing to that directory, then yes I'm not sure what issue is occurring on your machine.

**Comment by lorvent** [comment]
Sorry... you are correct,

both are different directories and key is different in both places.

its working properly now :+1:

**Comment by jmayday** [comment]
Is it correct to simply link?
```
ln -s ~/.ssh /home/<user>/.ssh 
```

* ~is our home pointing to Users\<user> (Windows home directory for given user)
