### ISSUE TITLE
Babun not working with Sass

### ISSUE THREAD

**Issue by jeffreysbrother** [babun/babun#566]
I was able to successfully install and use Sass from the Windows Command Prompt. I'm running ruby 2.1.7p400 (2015-0-18 revision 51632) [i386-mingw32] . . . and Sass 3.4.21 (Selective Steve).

When I run "sass -v" from Babun, I get this:
C:\Ruby21\bin\ruby.exe: No such file or directory -- /cygdrive/c/Ruby21/bin/sass (LoadError)

(I am using Windows 10, by the way)

**Comment by codenotfound** [comment]
Just had the same problem, turns out all you need is "alias sass=sass.bat" in babun's bash_rc
Do note that I have ruby installed from official site, not through babun's pact manager.

Proof that it works: 
![babun](https://cloud.githubusercontent.com/assets/3008203/14411962/50798466-ff5f-11e5-8541-ed285f58aedf.png)

**Comment by codenotfound** [comment]
Btw take a look at #93 for more detailed discussion

**Comment by jeffreysbrother** [comment]
@codenotfound thank you so much!
