### ISSUE TITLE
ConEmu shortcuts don't work with babun?

### ISSUE THREAD

**Issue by Ashtonian** [babun/babun#641]
I have setup chrome like new tab and close tab shortcuts in conemu and I am trying to use babun with it. Whenever I'm in the babun shell the shortcuts don't seem to get passed to ConEmu - any ideas?

The shortcuts in question are:

```
Ctrl+T
Ctrl+W
```

**Comment by tgroff** [comment]
I've experienced this as well.  Since CTRL+w is a bash/zsh command to _clear the previous word_, that's what takes precedence in Babun.  Seems to be nothing we can do about it for now.

See this related issue:
https://github.com/babun/babun/issues/572#issuecomment-190411201

ConEmu  Hotkey Limitations
http://conemu.github.io/en/ChildGui.html#hotkeys

**Comment by iMingLei** [comment]
After set **[Focus in child windows](https://conemu.github.io/en/SettingsChildGui.html#settings-children-gui)** off and enable "**[Intercept Keys](https://conemu.github.io/en/SettingsKeyboard.html#settings-keyboard)**" in ConEmu, these hotkeys work like a charm.

**Comment by Ashtonian** [comment]
Awesome - that worked for me as well - thanks!
