### ISSUE TITLE
Running Windows Applications That Call Executables With Backslashes

### ISSUE THREAD

**Issue by Nezteb** [babun/babun#691]
Long story short: I've install the ChefDK onto my Windows machine.

When I run `chef` from Babun, I get:

```
>> chef
C:\opscode\chefdk\embedded\bin\ruby.exe: No such file or directory -- /cygdrive/c/opscode/chefdk/bin/chef (LoadError)
```

This seems to be because the `chef` executable is calling its embedded Ruby using regular Windows backslashed paths.

From what I've researched, Babun strips backslashes:

```
>> cd C:\opscode\chefdk\embedded\bin
bash: cd: C:opscodechefdkembeddedbin: No such file or directory
```

Obviously I can just use the Powershell terminal to use Chef, but I'd rather use Babun if it's possible.

Is there anyway to get Babun to work nicely with Windows applications that use backslashes without breaking everything else?

**Comment by jdriordan** [comment]
> From what I've researched, Babun strips backslashes:
Unix shells use backslashes to escape characters, '\n' is a newline '\\' is a literal backslash

Are you trying to run a program installed normal windows instead of cygwin? Generally this won't work (unless you can manually change paths with  `cygpath`. I this instance someone has helpfully made a workaround using aliases: http://russellcardullo.com/blog/2012/07/15/setting-up-chef-and-vagrant-on-windows-7-under-cygwin/

**Comment by Nezteb** [comment]
Sorry for the late response @jdriordan. The solution you linked is good enough for me; if I run into this again I can just alias it out. Thanks!
